package br.dev.andersonandrade.moedaOne.enuns;

/**
 * @author Anderson Andrade Dev
 * @Data de Criação 11/10/2024
 */
public enum Moeda {
  AED("Dirham dos Emirados Árabes Unidos", "Emirados Árabes Unidos"),
  AFN("Afegani Afegão", "Afeganistão"),
  ALL("Lek Albanês", "Albânia"),
  AMD("Dram Armênio", "Armênia"),
  ANG("Florim das Antilhas Neerlandesas", "Antilhas Neerlandesas"),
  AOA("Kwanza Angolano", "Angola"),
  ARS("Peso Argentino", "Argentina"),
  AUD("Dólar Australiano", "Austrália"),
  AWG("Florim Arubano", "Aruba"),
  AZN("Manat Azeri", "Azerbaijão"),
  BAM("Marco Conversível da Bósnia e Herzegovina", "Bósnia e Herzegovina"),
  BBD("Dólar de Barbados", "Barbados"),
  BDT("Taka de Bangladesh", "Bangladesh"),
  BGN("Lev Búlgaro", "Bulgária"),
  BHD("Dinar do Bahrein", "Bahrein"),
  BIF("Franco Burundês", "Burundi"),
  BMD("Dólar das Bermudas", "Bermudas"),
  BND("Dólar do Brunei", "Brunei"),
  BOB("Boliviano", "Bolívia"),
  BRL("Real Brasileiro", "Brasil"),
  BSD("Dólar Bahamense", "Bahamas"),
  BTN("Ngultrum Butanês", "Butão"),
  BWP("Pula Botsuanense", "Botsuana"),
  BYN("Rublo Bielorrusso", "Belarus"),
  BZD("Dólar de Belize", "Belize"),
  CAD("Dólar Canadense", "Canadá"),
  CDF("Franco Congolês", "República Democrática do Congo"),
  CHF("Franco Suíço", "Suíça"),
  CLP("Peso Chileno", "Chile"),
  CNY("Renminbi Chinês", "China"),
  COP("Peso Colombiano", "Colômbia"),
  CRC("Colón Costarriquenho", "Costa Rica"),
  CUP("Peso Cubano", "Cuba"),
  CVE("Escudo Cabo-Verdiano", "Cabo Verde"),
  CZK("Coroa Tcheca", "República Tcheca"),
  DJF("Franco Djibutiano", "Djibuti"),
  DKK("Coroa Dinamarquesa", "Dinamarca"),
  DOP("Peso Dominicano", "República Dominicana"),
  DZD("Dinar Argelino", "Argélia"),
  EGP("Libra Egípcia", "Egito"),
  ERN("Nakfa Eritreia", "Eritreia"),
  ETB("Birr Etíope", "Etiópia"),
  EUR("Euro", "União Europeia"),
  FJD("Dólar Fijiano", "Fiji"),
  FKP("Libra das Ilhas Falkland", "Ilhas Falkland"),
  FOK("Coroa das Ilhas Faroé", "Ilhas Faroé"),
  GBP("Libra Esterlina", "Reino Unido"),
  GEL("Lari Georgiano", "Geórgia"),
  GGP("Libra de Guernsey", "Guernsey"),
  GHS("Cedi Ganês", "Gana"),
  GIP("Libra de Gibraltar", "Gibraltar"),
  GMD("Dalasi Gambiano", "Gâmbia"),
  GNF("Franco Guineense", "Guiné"),
  GTQ("Quetzal Guatemalteco", "Guatemala"),
  GYD("Dólar de Guiana", "Guiana"),
  HKD("Dólar de Hong Kong", "Hong Kong"),
  HNL("Lempira Hondurenha", "Honduras"),
  HRK("Kuna Croata", "Croácia"),
  HTG("Gourde Haitiano", "Haiti"),
  HUF("Florim Húngaro", "Hungria"),
  IDR("Rupia Indonésia", "Indonésia"),
  ILS("Novo Shekel Israelense", "Israel"),
  IMP("Libra da Ilha de Man", "Ilha de Man"),
  INR("Rupia Indiana", "Índia"),
  IQD("Dinar Iraquiano", "Iraque"),
  IRR("Rial Iraniano", "Irã"),
  ISK("Coroa Islandesa", "Islândia"),
  JEP("Libra de Jersey", "Jersey"),
  JMD("Dólar Jamaicano", "Jamaica"),
  JOD("Dinar Jordaniano", "Jordânia"),
  JPY("Iene Japonês", "Japão"),
  KES("Xelim Queniano", "Quênia"),
  KGS("Som Quirguiz", "Quirguistão"),
  KHR("Riel Cambojano", "Camboja"),
  KID("Dólar de Kiribati", "Kiribati"),
  KMF("Franco Comorense", "Comores"),
  KRW("Won Sul-Coreano", "Coreia do Sul"),
  KWD("Dinar Kuwaitiano", "Kuwait"),
  KYD("Dólar das Ilhas Cayman", "Ilhas Cayman"),
  KZT("Tenge Cazaque", "Cazaquistão"),
  LAK("Kip Lao", "Laos"),
  LBP("Libra Libanesa", "Líbano"),
  LKR("Rupia Cingalesa", "Sri Lanka"),
  LRD("Dólar Liberiano", "Libéria"),
  LSL("Loti Lesotiano", "Lesoto"),
  LYD("Dinar Líbio", "Líbia"),
  MAD("Dirham Marroquino", "Marrocos"),
  MDL("Leu Moldavo", "Moldávia"),
  MGA("Ariary Malgaxe", "Madagáscar"),
  MKD("Dinar Macedônio", "Macedônia do Norte"),
  MMK("Quiate Birmanês", "Mianmar"),
  MNT("Tugrik Mongol", "Mongólia"),
  MOP("Pataca Macaense", "Macau"),
  MRU("Ouguiya Mauritana", "Mauritânia"),
  MUR("Rupia Mauriciana", "Maurícia"),
  MVR("Rufiyaa Maldiva", "Maldivas"),
  MWK("Kwacha Malawiano", "Malawi"),
  MXN("Peso Mexicano", "México"),
  MYR("Ringgit Malaio", "Malásia"),
  MZN("Metical Moçambicano", "Moçambique"),
  NAD("Dólar Namíbio", "Namíbia"),
  NGN("Naira Nigeriana", "Nigéria"),
  NIO("Córdoba Nicaraguense", "Nicarágua"),
  NOK("Coroa Norueguesa", "Noruega"),
  NPR("Rupia Nepalesa", "Nepal"),
  NZD("Dólar Neozelandês", "Nova Zelândia"),
  OMR("Rial Omanense", "Omã"),
  PAB("Balboa Panamenho", "Panamá"),
  PEN("Sol Peruano", "Peru"),
  PGK("Kina Papuásia", "Papua-Nova Guiné"),
  PHP("Peso Filipino", "Filipinas"),
  PKR("Rupia Paquistanesa", "Paquistão"),
  PLN("Złoty Polonês", "Polônia"),
  PYG("Guarani Paraguaio", "Paraguai"),
  QAR("Rial Catarense", "Catar"),
  RON("Leu Romeno", "Romênia"),
  RSD("Dinar Sérvio", "Sérvia"),
  RUB("Rublo Russo", "Rússia"),
  RWF("Franco Ruandês", "Ruanda"),
  SAR("Riyal Saudita", "Arábia Saudita"),
  SBD("Dólar das Ilhas Salomão", "Ilhas Salomão"),
  SCR("Rupia de Seychelles", "Seicheles"),
  SDG("Libra Sudanesa", "Sudão"),
  SEK("Coroa Sueca", "Suécia"),
  SGD("Dólar de Singapura", "Singapura"),
  SHP("Libra de Santa Helena", "Santa Helena"),
  SLE("Leone de Serra Leoa", "Serra Leoa"),
  SOS("Xelim Somali", "Somália"),
  SRD("Dólar do Suriname", "Suriname"),
  SSP("Libra Sudanesa do Sul", "Sudão do Sul"),
  STN("Dobra Santomense", "São Tomé e Príncipe"),
  SYP("Libra Síria", "Síria"),
  SZL("Lilangeni Suazilandês", "Eswatini"),
  THB("Baht Tailandês", "Tailândia"),
  TJS("Somoni Tadjique", "Tadjiquistão"),
  TMT("Manat Turcomeno", "Turcomenistão"),
  TND("Dinar Tunisiano", "Tunísia"),
  TOP("Paʻanga Tonganês", "Tonga"),
  TRY("Lira Turca", "Turquia"),
  TTD("Dólar de Trinidad e Tobago", "Trinidad e Tobago"),
  TVD("Dólar Tuvaluano", "Tuvalu"),
  TWD("Novo Dólar Taiwanês", "Taiwan"),
  TZS("Xelim Tanzaniano", "Tanzânia"),
  UAH("Hryvnia Ucraniana", "Ucrânia"),
  UGX("Xelim Ugandense", "Uganda"),
  USD("Dólar Americano", "Estados Unidos"),
  UYU("Peso Uruguaio", "Uruguai"),
  UZS("Som Uzbeque", "Uzbequistão"),
  VES("Bolívar Venezuelano", "Venezuela"),
  VND("Dong Vietnamita", "Vietnã"),
  VUV("Vatu Vanuatuense", "Vanuatu"),
  WST("Tala Samoana", "Samoa"),
  XAF("Franco CFA da África Central", "Estados da África Central"),
  XCD("Dólar do Caribe Oriental", "Estados do Caribe Oriental"),
  XOF("Franco CFA da África Ocidental", "Estados da África Ocidental"),
  XPF("Franco CFP", "Territórios Ultramarinos Franceses"),
  YER("Rial Iemenita", "Iêmen"),
  ZAR("Rand Sul-Africano", "África do Sul"),
  ZMW("Kwacha Zambiano", "Zâmbia"),
  ZWL("Dólar Zimbabuano", "Zimbábue");

  private final String nome;
  private final String pais;

  Moeda(String nome, String pais) {
    this.nome = nome;
    this.pais = pais;
  }

  public static Moeda buscarPorCodigo(String codigo) {
    for(Moeda moeda : Moeda.values()) {
      if(moeda.name().equalsIgnoreCase(codigo)) {
        return moeda;
      }
    }
    throw new IllegalArgumentException("Moeda não encontrada: " + codigo);
  }

  public String getNome() {
    return nome;
  }

  public String getPais() {
    return pais;
  }

}
